In [1]:
# Use irise datasetfrom  seaborn and perform operation
# Use MultinomialNB, BernomialNB

In [3]:
import pandas as pd
import seaborn as sns

In [5]:
tf = sns.load_dataset('iris')
tf

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
tf.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [7]:
tf.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
# Prepare data

tf.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
tf.shape

(150, 5)

In [10]:
tf.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [13]:
tf.species.unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [37]:
new_tf = pd.get_dummies(tf['species'],drop_first=True)
new_tf

1      2
0    False  False
1    False  False
2    False  False
3    False  False
4    False  False
..     ...    ...
145  False   True
146  False   True
147  False   True
148  False   True
149  False   True

[150 rows x 2 columns]

In [17]:
result_tf = pd.concat([tf,new_tf],axis=1)
result_tf

sepal_length  sepal_width  petal_length  petal_width    species  setosa  \
0             5.1          3.5           1.4          0.2     setosa    True   
1             4.9          3.0           1.4          0.2     setosa    True   
2             4.7          3.2           1.3          0.2     setosa    True   
3             4.6          3.1           1.5          0.2     setosa    True   
4             5.0          3.6           1.4          0.2     setosa    True   
..            ...          ...           ...          ...        ...     ...   
145           6.7          3.0           5.2          2.3  virginica   False   
146           6.3          2.5           5.0          1.9  virginica   False   
147           6.5          3.0           5.2          2.0  virginica   False   
148           6.2          3.4           5.4          2.3  virginica   False   
149           5.9          3.0           5.1          1.8  virginica   False   

     versicolor  virginica  
0         False      False  
1         False      False  
2         False      False  
3         False      False  
4         False      False  
..          ...        ...  
145       False       True  
146       False       True  
147       False       True  
148       False       True  
149       False       True  

[150 rows x 8 columns]

In [18]:
from sklearn.preprocessing import LabelEncoder

In [21]:
#Use species test to numerical conversion

lb = LabelEncoder()

In [31]:
tf['species'] = lb.fit_transform(tf['species'])
tf

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [33]:
lb.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [32]:
tf.

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

# Seperatout Input and Output

In [38]:
tf


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [54]:
# Input
inp = tf.iloc[:,0:4]
inp

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [58]:
# Output
out = tf.species
out

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int32

In [61]:
from sklearn.naive_bayes import BernoulliNB,MultinomialNB

In [63]:
bnb = BernoulliNB()
mnb= MultinomialNB()


mnb.fit(inp,out)

MultinomialNB()

In [64]:
bnb.fit(inp,out)

BernoulliNB()

In [65]:
tf[34:35]

sepal_length  sepal_width  petal_length  petal_width  species
34           4.9          3.1           1.5          0.2        0

In [66]:
# Prediction

bnb.predict([[4.9,3,1.4,0.2]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([0])

In [67]:
bnb.predict([[6.7,3.0,5.2,2.3]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([0])

In [68]:
tf.sample(5)

sepal_length  sepal_width  petal_length  petal_width  species
77           6.7          3.0           5.0          1.7        1
1            4.9          3.0           1.4          0.2        0
14           5.8          4.0           1.2          0.2        0
15           5.7          4.4           1.5          0.4        0
89           5.5          2.5           4.0          1.3        1

In [69]:
bnb.predict([[6.7,3.0,5,1.7]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([0])

In [71]:
bnb.predict_proba([[6.7,3.0,5,1.7]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([[0.33333333, 0.33333333, 0.33333333]])

In [72]:
bnb.predict_proba([[6.7,3.0,5.2,2.3]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BernoulliNB was fitted with feature names
  warnings.warn(


array([[0.33333333, 0.33333333, 0.33333333]])

In [73]:
bnb.score(inp,out)*100

33.33333333333333

In [75]:
mnb.predict([[4.9,3,1.4,0.2]]) 

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([0])

In [77]:
mnb.predict([[5.5,2.5,4,1.3]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1])

In [78]:
mnb.predict([[6.7,3.0,5.0,1.7]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1])

In [79]:
mnb.predict_proba([[6.7,3.0,5.0,1.7]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([[0.0252505 , 0.49379693, 0.48095257]])

In [80]:
mnb.score(inp,out)*100

95.33333333333334

In [81]:
mnb.predict_proba([[5.5,2.5,4,1.3]])

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([[0.05277102, 0.48714466, 0.46008433]])

In [82]:
mnb.score(inp,out)*100

95.33333333333334